config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:show]
  
  resources :services do
    post :import, on: :collection
    resources :clips, only: [:create, :destroy]
  end
  
  resources :subscriptions, except: [:index]

  resources :contacts, only: [:new, :create]
end

app/models/service.rb
class Service < ApplicationRecord
  extend OrderAsSpecified

  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions, source: :user
  has_many :categorizings, dependent: :destroy
  has_many :categories, through: :categorizings, source: :category
  has_many :clips
  has_many :clipped_users, through: :clips, source: :user

  belongs_to :user

  validates :name, presence: true, uniqueness: true, length: { maximum: 30 }
  validates :summary, presence: true, length: { maximum: 255 }
  validates :link, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true

  mount_uploader :icon, IconUploader

  enum status: { open: 0, secret: 9, development: 5 }

  scope :search_with_category, ->(category_id) { where(id: category_ids = Categorizing.where(category_id: category_id).pluck(:service_id)) }
  scope :search_open_status, -> { where(status: 0) }
  scope :search_secret_status, -> { where(status: 9) }
  scope :search_with_user_id, ->(user) { where(user_id: user.id) }
  scope :search_with_using, ->(user) { where(id: user.subscriptions.map(&:service_id)) }
  scope :search_with_unregisterd, ->(user) { where(id: Subscription.where(charge: 0).where(user_id: user.id).map(&:service_id)) }
  scope :sort_name, -> { order('LOWER(name)') }
  scope :sort_create, -> { order(created_at: :desc) }
  scope :sort_update, -> { order(updated_at: :desc) }

  class << self
    # 検索メソッド
    def search(search)
      return where(['name ILIKE ?', "%#{search}%"]) if search

      all
    end

    # 利用者数順にソート
    def sort_with_user_count
      using_count = Subscription.group(:service_id).count
      service_ids = Hash[using_count.sort_by { |_, v| -v }].keys
      where(id: service_ids).where(status: 0).order_as_specified(id: service_ids)
    end

    # 料金順にソート
    def sort_charge
      service_ids = Subscription.order(charge: :desc).map(&:service_id)
      where(id: service_ids).order_as_specified(id: service_ids)
    end

    # 支払順にソート
    def sort_date
      service_ids = Subscription.order(due_date: :asc).map(&:service_id)
      where(id: service_ids).order_as_specified(id: service_ids)
    end

    # CSVエクスポート
    def csv_attributes
      %w[name summary link user_id created_at updated_at]
    end

    def generate_csv
      CSV.generate(headers: true) do |csv|
        csv << csv_attributes
        all.find_each do |service|
          csv << csv_attributes.map { |attr| service.send(attr) }
        end
      end
    end

    # CSVインポート
    def import(file)
      CSV.foreach(file.path, headers: true) do |row|
        service = Service.new
        service.attributes = row.to_hash.slice(*csv_attributes)
        service.save!
      end
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :required_creator, only: %i[edit update destroy]
  before_action :check_file, only: %i[import]
  PER_PAGE = 12

  def index
    @services = Service.search_open_status
    # @clip = current_user.clips.build
    # カテゴリーで絞り込み
    @services = @services.search_with_category(params[:category_id]) if params[:category_id]

    # 検索機能
    @services = @services.search(params[:search]) if params[:search]

    # ソート機能
    @services = @services.sort_name if params[:sort_name] # 名前順
    @services = @services.sort_create if params[:sort_create] # 新着順
    @services = @services.sort_update if params[:sort_update] # 更新順
    @services = @services.sort_with_user_count if params[:sort_with_rank] # 人気順
    @services = @services.search_with_using(current_user) if params[:search_with_using] # 利用中のみ
    @services = current_user.clipped_services if params[:sort_clipped] # 気になるサービスのみ
    @services = Service.search_secret_status.search_with_user_id(current_user) if params[:sercet_index] # オリジナルのみ

    # CSV出力
    respond_to do |format|
      format.html
      format.csv { send_data @services.generate_csv, filename: "service-#{Time.zone.now.strftime('%Y%m%d%S')}.csv" }
    end

    # ページネーション
    @services = @services.page(params[:page]).per(PER_PAGE).sort_name.includes(:categories)
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user_id = current_user.id
    @service.status = 'secret' unless current_user.admin?
    if @service.save
      Subscription.create(user_id: current_user.id, service_id: @service.id) if @service.status == 'secret'
      redirect_to services_path, notice: "「#{@service.name}」を登録しました"
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @service.update(service_params)
      redirect_to services_path, notice: "「#{@service.name}」を更新しました"
    else
      render 'edit'
    end
  end

  def destroy
    @service.destroy
    redirect_to services_path, alert: "「#{@service.name}」を削除しました"
  end

  # CSVインポート
  def import
    Service.import(params[:file])
    redirect_to services_path, notice: 'CSVをインポートしました'
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(
      :name, :icon, :icon_cache, :link, :summary, :status, category_ids: []
    )
  end

  def check_file
    redirect_to services_path, alert: 'CSVファイルを選択してください' if params[:file].nil?
  end
end

app/helpers/services_helper.rb
module ServicesHelper
  include Common
  def total_services(services)
    services.count
  end

  # 追加されたサブスクリプションかどうか
  def already_added?(service)
    subscriptions.where(service_id: service.id).present?
  end

  def categories
    Category.all
  end

  # 気になるサービスをクリップしているかどうか
  def already_clipped?(service)
    current_user.clips.exists?(service_id: service.id)
  end

  def clip(service)
    current_user.clips.find_by(service_id: service.id)
  end
end

app/views/services/_add.html.erb
<% if already_added?(service) %>
  <span id="minus-btn">
    <%= link_to subscription_path(id: get_subscription_id(current_user, service)), method: :delete,"data-toggle" => "popover", "data-content" => "外す", remote: true, class: "btn btn-light detail-info" do %>
      <%= fa_icon "minus" %>
    <% end %>
  </span>
<% else %>
  <span id="plus-btn">
    <%= link_to new_subscription_path(service_id: service.id),"data-toggle" => "popover", "data-content" => "追加", remote: true, class: "btn btn-secondary detail-info" do %>
      <%= fa_icon "plus" %>
    <% end %>
  </span>
<% end %>

app/views/services/_category.html.erb
<div class="card mb-4">
  <div class="card-header p-0 pl-2 pt-2">
    <h6 class="ml-2">カテゴリー</h6>
  </div>
  <div class="card-body">
    <span><%= link_to 'All', services_path, class: "badge badge-light py-1 px-2 category-badge" %></span>
    <% categories.each do |category| %>
      <span><%= link_to category.name, services_path(category_id: category.id), class: "badge badge-light py-1 px-2 category-badge" %></span>
    <% end %>
  </div>
</div>

app/views/services/_csv.html.erb
<button type="button" class="btn btn-info ml-3" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    CSV関連表示
</button>
<div class="collapse" id="collapseExample">
  <div class="row">
    <div class="col-md-9">
      <%= form_tag import_services_path, multipart: true do %>
        <div class="row input-inline">
          <div class="col-md-9">
            <div class="input-group">
              <label class="input-group-prepend">
                <span class="btn btn-secondary">
                  ファイル選択<%= file_field_tag :file, style: "display:none;" %>
                </span>
              </label>
              <%= text_field_tag :text, "", class: "form-control csv-text", readonly: "" %>
            </div>
          </div>
          <div class="col-md-3">
            <div class="input-group">
              <%= submit_tag "CSVインポート", class: "btn btn-info" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-3">
      <%= link_to 'CSVエクスポート', services_path(format: :csv), class: "btn btn-success mb-3" %>
    </div>
  </div>
</div>

app/views/services/_form.html.erb
<div class="container service-form show-page">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-9 mx-auto mb-3">
      <% if @service.errors.any? %>
        <div id="error_explanation">
          <h2><%= @service.errors.count %>件のエラーがあります。</h2>
          <ul>
            <% @service.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="card">
        <h2 class="form-title">
          <% if params[:id] %>
            サービス編集
          <% else %>
            サービス登録
          <% end %>
        </h2>
        <%= form_with model: @service, local: true do |f| %>
          <div class="card-body">
            <div class="row d-flex align-items-center">
              <div class="col-md-3">
                <div class="form-item mb-2">
                
                  <div id="icon_field" onClick="$('#file').click()" >
                    <% if @service.icon.url.present? %>
                      <%= image_tag(@service.icon.url) %>
                    <% end %>
                    <div class="mask">
                      <div class="caption">アイコン</div>
                    </div>
                  </div>
                  <%= f.file_field :icon, class: "icon", style: "display:none;", id: "file" %>
                  <%= f.hidden_field :icon_cache %>
                </div>
              </div>
              <div class="col-xs-12 col-md-9">
                <div class="form-label-group mb-2" id="service-name-box">
                  <%= f.text_field :name, placeholder: "サービス名", required: true, class: "form-control service-name" %>
                </div>
              </div>
            </div>
            <%# .row1 %>

            <div class="row my-3">
              <div class="col-12">
                <div class="form-label-group mb-2">
                  <%= f.text_area :summary ,placeholder: "サービス概要", required: true,class: "form-control" ,rows: 5 %>
                </div>  
              </div>
            </div>
            <%# .row2 %>

            <div class="row mb-2">
              <div class="col-12">
                <div class="form-label-group mb-2">
                  <%= f.text_field :link, placeholder: "関連リンク", class: "form-control w-100" %> 
                </div>  
              </div>
            </div>
            <%# .row3 %>

            <div class="row">
              <div class="col-12">
                <div class="frame-box mb-2">
                  <span class="frame-title"><%= f.label :category_ids, 'カテゴリー(複数可)' %></span>
                  <p class="check-categories">
                    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, prompt: true do |l| %>
                      <span class="mx-1"><%= l.label { l.check_box + l.text } %></span>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>
            <%# .row4 %>

            <% if current_user.admin? %>
              <div class="form-label-group my-4">
                <div class="row">
                  <div class="label-notifiy col-md-3 text-center">
                    <span>公開範囲</span>
                  </div>
                  <div class="col-md-4 select-box select-plus">
                    <%= f.select :status, Service.statuses.keys.to_a, {}, class: "form-control" %>
                  </div>
                </div>
              </div>
            <% else %>
              <p class="text-danger ml-3 mt-3">登録したサービスは、他のユーザーには表示されません</p>
            <% end %>

            <div class="row mt-4">
              <div class="col-12">
                <div class="button-panel">
                  <%= f.submit class: "btn btn-lg btn-signin btn-block text-uppercase mt-3" %>
                </div>  
              </div>
            </div>
          </div>
          <%# .card-body %>
        <% end %>
      </div>
      <%# .card %>
    </div>
    <%# .col %>
  </div>
  <%# .row %>
</div>

app/views/services/_index_with_login.html.erb
<div class="row">
  <% if @services.blank? %>
    <p class="ml-5">
      一致する結果はありません。<br><br>
      <span class="h5"><%= link_to "サービス新規登録", new_service_path %>でオリジナルのサービスを登録できます！</span>
      (<span class="text-danger">他のユーザーには公開されません</span>)
    </p>
  <% end %>
  <% @services.each.with_index(1) do |service, i| %>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 mb-3 <%= "using-service" if already_added?(service) %>" id="subscription-<%= service.id %>">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              <% if service.icon.present? %>
                <div class="service-icon">
                  <%= image_tag service.icon.url %>
                </div>
              <% else %>
                <div class="no-icon">No-Icon</div>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="row category">
                <div class="col-md-12">
                  <% service.categories.each do |category|%>
                    <%= link_to category.name, services_path(category_id: category.id), class: "badge badge-primary py-1 px-2" %>
                  <% end %>
                </div>
                <div class="col-md-12">
                  <h5 class="service-title ommision"><%= service.name %></h5>
                </div>
              </div>
            </div>
          </div>
          <%# .row1 %>

          <div class="row mt-4">
            <div class="col-lg-7">
              <%= link_to service_path(service) ,remote: true, "data-toggle" => "popover", "data-content" => "詳細",class: "btn btn-info btn-circle detail-info mr-2 service-info-#{i}" do %>
                <%= fa_icon "info" %>
              <% end %>
              <%= link_to service.link, target: :blank, rel: "noopener", "data-toggle" => "popover", "data-content" => "関連リンク", class: "btn btn-link btn-circle detail-info"  do %>
                <%= fa_icon "link" %>
              <% end %>
              <span id="clip-btn-<%= service.id %>" class="clip-btn">
                <%= render 'clips/clip', { service: service }  %>
              </span>
            </div>
            <div class="col-lg-5 text-right mt-1">
              <span  data-toggle="popover", data-content="利用者数" class="detail-info mr-2">
                <%= fa_icon "users" , class: "mr-2 users-count" %>
                <span id="users-count-<%= service.id %>"><%= service.subscriptions.count %></span>
              </span>
              <span id="subscription-btn-<%= service.id %>">
                <%= render 'add', { service: service } %>
              </span>
            </div>
          </div>
          <%# .row2 %>
        </div>
        <%# .card-body %>
      </div>
      <%# .card %>
    </div>
    <%# .col %>
  <% end %>
</div>
<%# .row %>
<div id="subscription-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/services/_index_with_logout.html.erb
<div class="row">
  <% if @services.blank? %>
    <p>一致する結果はありません</p>
  <% end %>
  <% @services.each do |service| %>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 mb-3">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              <% if service.icon.present? %>
                <div class="service-icon">
                  <%= image_tag service.icon.url %>
                </div>
              <% else %>
                <div class="no-icon">No-Icon</div>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="row category">
                <div class="col-md-12">
                  <% service.categories.each do |category|%>
                    <%= link_to category.name, services_path(category_id: category.id), class: "badge badge-primary py-1 px-2" %>
                  <% end %>
                </div>
                <div class="col-md-12">
                  <h5 class="service-title ommision"><%= service.name %></h5>
                </div>
              </div>
            </div>
          </div>
          <%# .row1 %>
          <div class="row mt-3">
            <div class="col-md-9">
              <%= link_to service_path(service) ,remote: true, "data-toggle" => "popover", "data-content" => "詳細",class: "btn btn-info btn-circle detail-info mr-2" do %>
                <%= fa_icon "info" %>
              <% end %>
              <%= link_to service.link, target: :blank, rel: "noopener", "data-toggle" => "popover", "data-content" => "関連リンク", class: "btn btn-link btn-circle detail-info mr-2"  do %>
                <%= fa_icon "link" %>
              <% end %>
            </div>
            <div class="col-md-3 text-right mt-2">
              <span  data-toggle="popover", data-content="利用者数" class="detail-info">
                <%= fa_icon "users" , class: "mr-2" %><%= service.subscriptions.count %>
              </span>
            </div>
          </div>
          <%# .row2 %>
        </div>
        <%# .card-body %>
      </div>
      <%# .card %>
    </div>
    <%# .col %>
  <% end %>
</div>
<%# .row %>

app/views/services/_search.html.erb
<div class="col-md-5">
  <%= form_tag(services_path, method: 'get',class: "form-inline" ) do %>
    <%= text_field_tag :search ,"",placeholder: "サービス名",class: "form-control search-form w-50"%>
    <div class="input-group-append">
      <%= submit_tag '検索', :name => nil, class: "btn btn-outline-secondary ml-2" %>
      <%= link_to 'クリア', services_path, class: "btn btn-outline-secondary ml-2" %>
    </div>
  <% end %>
</div>

<div class="col-md-7 text-right">
  <%= link_to '人気順', services_path(sort_with_rank: "true"), class: "btn btn-outline-secondary #{params[:sort_with_rank] ? 'disabled' : ''}" %>
  <%= link_to '新着順', services_path(sort_create: "true"), class: "btn btn-outline-secondary ml-2 #{params[:sort_create] ? 'disabled' : ''}" %>
  <% if current_user&.admin? %>
    <%= link_to '更新順', services_path(sort_update: "true"), class: "btn btn-outline-secondary ml-2 #{params[:sort_update] ? 'disabled' : ''}" %>
  <% elsif current_user %>
    <%= link_to '気になる', services_path(sort_clipped: "true"), class: "btn btn-outline-secondary ml-2 #{params[:sort_clipped] ? 'disabled' : ''}" %>
    <%= link_to '利用中のみ', services_path(search_with_using: "true"), class: "btn btn-outline-secondary ml-2 #{params[:search_with_using] ? 'disabled' : ''}" %>
    <%= link_to 'オリジナル', services_path(sercet_index: "true"), class: "btn btn-outline-secondary ml-2 #{params[:sercet_index] ? 'disabled' : ''}" %>
  <% end %>
</div>

app/views/services/_show.html.erb
<div class="container show-page">
  <div class="row mb-5">
    <div class="col-12 mb-3">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="card p-3">
            <button type="button" class="close text-right" data-dismiss="modal" onfocus="this.blur();">&times;</button>
            <div class="card-body">
              <div class="row">
                <div class="col-md-4 ml-3">
                  <% if @service.icon.present? %>
                    <div class="service-icon">
                      <%= image_tag @service.icon.url %>
                    </div>
                  <% else %>
                    <div class="no-icon">No-Icon</div>
                  <% end %>
                </div>
                <div class="col-md-7">
                  <div class="row category">
                    <div class="col-md-12">
                      <% @service.categories.each do |category|%>
                        <span class= "badge badge-primary py-1 px-2"><%= category.name %></span>
                      <% end %>
                    </div>
                    <div class="col-md-12">
                      <h3 class="service-title"><%= @service.name %></h3>
                    </div>
                  </div>
                </div>
              </div>
              <%# .row1 %>

              <div class="row">
                <div class="col-12">
                  <div class="frame-box mb-2">
                    <span class="frame-title">Summary</span>
                    <p><%= simple_format(@service.summary) %></p>
                  </div>
                </div>
              </div>
              <%# .row2 %>

              <div class="row d-flex align-items-center mt-4">
                <div class="col-md-7">
                  <%= link_to @service.link, target: :blank, rel: "noopener", "data-toggle" => "popover", "data-content" => "関連リンク", class: "btn btn-link btn-circle detail-info mr-2"  do %>
                    <%= fa_icon "link" %>
                  <% end %>
                  <% if current_user&.admin? || @service.status == "secret" %>
                    <%= link_to edit_service_path(@service) ,class: "btn btn-success btn-circle service-edit mr-2" do %>
                      <%= fa_icon "pen" %>
                    <% end %>
                    <%= link_to service_path(@service), method: :delete, data: { confirm: '本当に削除してもいいですか?' } ,class: "btn btn-danger btn-circle delete" do %>
                      <%= fa_icon "trash" %>
                    <% end %>
                  <% end %>
                </div>
                <div class="col-md-5 text-right mt-3">
                  <span  data-toggle="popover", data-content="利用者数" class="detail-info">
                    <%= fa_icon "users" , class: "mr-2" %><%= @service.subscriptions.count %>
                  </span>
                </div>
              </div>
              <%# .row3 %>
            </div>
            <%# .card-body %>
          </div>
          <%# .card %>
        </div>
        <%# .modal-content %>
      </div>
      <%# .modal-dialog %>
    </div>
    <%# .col %>
  </div>
  <%# .row %>
</div>
<%# .container %>

app/views/services/edit.html.erb
<% provide(:title, "Edit Service") %>
<div class="container">
  <div class="new-form">
    
    <%= render 'form' %>
    
  </div>
</div>

app/views/services/index.html.erb
<% provide(:title, "Services") %>
<div class="container">
  <% if current_user %>
    <%= link_to 'サービス新規登録', new_service_path, class: "btn btn-new my-3" %>
  <% end %>
  <% if current_user.try(:admin?) %>
    <%= render 'csv' %>
  <% end %>

  <%= render 'category' %>

  <div class="row mb-4 pb-3 border-bottom">
    <%= render 'search' %>
  </div>

  <div class="services">
    <div class="row border-bottom mb-4">
      <div class="col-md-9">
        <%= paginate @services %>
      </div>
      <div class="col-md-3 text-right pt-3">
        <span>表示件数: <%= total_services(@services) %>件 / <%= @services.total_count %>件中</span>
      </div>
    </div>
    <% if current_user %>
      <%= render 'index_with_login' %>
    <% else %>
      <%= render 'index_with_logout' %>
    <% end %>
  </div>
</div>
<div id="service-show-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/services/new.html.erb
<% provide(:title, "New Service") %>
<div class="container">
  <div class="new-form">
    
    <%= render 'form' %>
    
  </div>
</div>

app/views/services/show.js.erb
$("#service-show-modal").html("<%= escape_javascript(render 'show') %>")
$("#service-show-modal").modal("show")