config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:show]
  
  resources :services do
    post :import, on: :collection
    resources :clips, only: [:create, :destroy]
  end
  
  resources :subscriptions, except: [:index]

  resources :contacts, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :services, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :services, through: :subscriptions, source: :service
  has_many :clips, dependent: :destroy
  has_many :clipped_services, through: :clips, source: :service

  validates :name, presence: true, length: { maximum: 30 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google]

  enum notification_status: { notifications_off: 0, notifications_one: 1, notifications_two: 2 }

  scope :search_with_category, ->(category_id) { where(id: category_ids = Categorizing.where(category_id: category_id).select(:service_id)) }
  scope :sort_name, -> { order(name: :asc) }
  scope :sort_create, -> { order(created_at: :desc) }

  class << self
    # 検索メソッド
    def search(search)
      return where(['name LIKE ?', "%#{search}%"]) if search

      all
    end

    # oauth認証
    def from_omniauth(auth)
      user = User.find_by(email: auth.info.email)
      user ||= User.new(
        email: auth.info.email,
        provider: auth.provider,
        uid: auth.uid,
        name: auth.info.name,
        password: Devise.friendly_token[0, 20]
      )
      user.save
      user
    end

    # 新規登録時にuidカラムをランダムに自動生成
    def create_unique_string
      SecureRandom.uuid
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: provider.to_s.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # 新規登録時にUIDカラムを自動生成
  def build_resource(hash = {})
    hash[:uid] = User.create_unique_string
    super
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # 編集後、ユーザー詳細画面へ遷移
  def after_update_path_for(_resource)
    user_path(id: current_user.id)
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Common
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:show]
  PER_PAGE = 10

  def show
    @subscriptions = subscriptions
    @services = current_user.services

    # 検索機能
    @services = @services.search(params[:search]) if params[:search]

    # ソート機能
    @services = @services.sort_name if params[:sort_name] # 名前順
    @services = @services.sort_create if params[:sort_create] # 新着順
    @services = @services.search_with_unregisterd(current_user) if params[:sort_unregistered] # 詳細未登録のみ
    @services = @services.sort_charge if params[:sort_charge] # 利用料金順
    @services = @services.sort_date if params[:sort_date] # 支払日順

    # ページネーション
    @services = @services.page(params[:page]).per(PER_PAGE).includes(:categories)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def subscription(user, service)
    Subscription.find_by(user_id: user.id, service_id: service.id)
  end

  def total_subscription_count(user)
    user.subscriptions.count
  end
end

app/views/users/_first_visit_page.html.erb
<div class="help-page">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="help-title text-center">Welcom to Subsc</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h5 class="help-subtitle">STEP① 利用しているサービスを探そう</h5>
          <p class="help-text"> 
            <%= link_to "サービス一覧ページ", services_path %>
            で利用しているサービスを探してみよう。<br>
            利用しているサービスが見つからない場合は、自分で作成もできます。<br>
            自分で作成したサービスは他のユーザーには見られないので安心です。
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h5 class="help-subtitle">STEP② 追加ボタンを押そう</h5>
          <p class="help-text"> 
            各サービスの右下にプラスマークの追加ボタンがあります。<br>
            利用しているサービスが見つかったら、追加ボタンを押してみよう。<br>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h5 class="help-subtitle">STEP③ 利用料金を入力しよう</h5>
          <p class="help-text"> 
            追加ボタンを押すと、登録画面に移動します<br>
            画面が表示されたら、利用料金や支払日を入れて登録ボタンを押してください<br>
            もちろん何も変更せず登録ボタンを押して、あとで編集もできます。
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h5 class="help-subtitle">STEP④ 合計の利用料金や通知頻度を確認してみよう</h5>
          <p class="help-text"> 
            マイページの左側に合計利用料金や通知頻度が表示されています。<br>
            通知オンの場合は、毎月1日にメールが届きます。正しいメールアドレスかどうか確認してください。<br>
            また、通知頻度を変更できるので、不要であればオフにしてください。
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_search.html.erb
<div class="row mb-4 pb-3 border-bottom">
  <div class="col-md-6">
    <%= form_tag(user_path, method: 'get',class: "form-inline" ) do %>
      <%= text_field_tag :search ,"",placeholder: "サービス名",class: "form-control search-form w-50"%>
      <div class="input-group-append">
        <%= submit_tag '検索', :name => nil, class: "btn btn-outline-secondary ml-2" %>
        <%= link_to 'クリア', user_path, class: "btn btn-outline-secondary ml-2" %>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 text-right">
    <%= link_to '名前順', user_path(sort_name: "true"), class: "btn btn-outline-secondary #{params[:sort_name] ? 'disabled' : ''}" %>
    <%= link_to '新着順', user_path(sort_create: "true"), class: "btn btn-outline-secondary ml-2 #{params[:sort_create] ? 'disabled' : ''}" %>
    <%= link_to '利用料金順', user_path(sort_charge: "true"), class: "btn btn-outline-secondary ml-2 #{params[:sort_charge] ? 'disabled' : ''}" %>
    <%= link_to '支払日順', user_path(sort_date: "true"), class: "btn btn-outline-secondary ml-2 #{params[:sort_date] ? 'disabled' : ''}" %>
    <%= link_to '未登録のみ', user_path(sort_unregistered: "true"), class: "btn btn-outline-secondary ml-2 #{params[:sort_unregistered] ? 'disabled' : ''}" %>
  </div>
</div>

app/views/users/_subscription.html.erb
<div class="row">
  <% @services.each.with_index(1) do |service, i| %>
    <div class="col-12 mb-3">
      <div class="card">
        <div class="card-body">
          <div class="row d-flex align-items-center">
            <div class="col-md-2">
              <% if service.icon.present? %>
                <div class="service-icon">
                  <%= image_tag service.icon.url %>
                </div>
              <% else %>
                <div class="no-icon">No-Icon</div>
              <% end %>
            </div>
            <div class="col-md-4">
              <p>
                <% service.categories.each do |category|%>
                  <span class="badge badge-primary p-1 px-2"><%= category.name %></span>
                <% end %>
              </p>
              <h5 class="service-title ommision"><%= service.name %></h5>
            </div>
            <% subscription = subscription(current_user, service) %>
            <div class="col-md-3">
              <div class="row subsc-info">
                <div class="col-md-12 mb-3">
                  <%= fa_icon "file-invoice-dollar" %><span class="charge-item ml-2"><%= subscription.charge %>円</span>
                </div>
                <div class="col-md-12">
                  <%= fa_icon "calendar-check" %><span class="due-date-item ml-2"><%= subscription.due_date %>日</span>
                </div>
              </div>
            </div>
            <div class="col-md-3 subsc-btn-menu">
              <%= link_to subscription_path(subscription),remote: true, class: "btn btn-info btn-circle subsc-info-#{i} mr-2" do %>
                <%= fa_icon "info" %>
              <% end %>
              <%= link_to edit_subscription_path(subscription), class: "btn btn-success btn-circle subsc-edit-#{i} mr-2" do %>
                <%= fa_icon "pen" %>
              <% end %>
              <%= link_to subscription_path(subscription, back_to_mypage: "true"), method: :delete,data: { confirm: '本当に解除してもいいですか?' }, class: "btn btn-danger btn-circle subsc-delete-#{i}" do %>
                <%= fa_icon "minus" %>
              <% end %>
            </div>
          </div>
        </div>
        <%# .card-body %>
      </div>
      <%# .card %>
    </div>
    <%# .col %>
  <% end %>
</div>
<%# .row %>

app/views/users/_subscriptions.html.erb
<div class="row">
  <% @services.each do |service| %>
    <div class="col-12 mb-3">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-2 img-height">
              <% if service.icon.present? %>
                <%= image_tag service.icon.thumb.url %>
              <% else %>
                No-Icon
              <% end %>
            </div>
            <div class="col-md-4 subsc-title">
              <p>
                <% service.categories.each do |category|%>
                  <span class="badge badge-primary p-1 px-2"><%= category.name %></span>
                <% end %>
              </p>
              <h5><%= service.name %></h5>
            </div>

            <% subsc_subscription = subscription(service) %>
            <% if subsc_subscription %>
              <div class="col-md-2">
                <%= subsc_subscription.charge %>
              </div>
              <div class="col-md-2">
                <%= subsc_subscription.due_date %>日
              </div>
              <div class="col-md-2">
                <%= link_to subscription_path(service_id: service.id), class: "btn btn-info mr-2" do %>
                  <%= fa_icon "info" %>
                <% end %>
                <%= link_to edit_subscription_path(service_id: service.id) ,class: "btn btn-success mr-2" do %>
                  <%= fa_icon "pencil" %>
                <% end %>
                <%= link_to subscription_path(subsc_subscription,back_to_mypage: "true"), method: :delete,data: { confirm: '本当に解除してもいいですか?' }, class: "btn btn-danger" do %>
                  <%= fa_icon "minus" %>
                <% end %>
              </div>
            <% else %>
              <div class="col-md-2">未登録</div>
              <div class="col-md-2">未登録</div>
              <div class="col-md-2">
                <%= link_to new_subscription_path(service_id: service.id), 'data-toggle' => "popover", 'data-content' => "詳細登録" ,'data-placement'=> "bottom" ,class: "subscription-info btn btn-primary mr-2" do %>
                  <%= fa_icon "plus" %>
                <% end %>
                <%= link_to subscription_path(service, id: current_user.id, back_to_mypage: "true"), method: :delete,data: { confirm: '本当に解除してもいいですか?' }, class: "btn btn-danger" do %>
                  <%= fa_icon "minus" %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <%# .card-body %>
      </div>
      <%# .card %>
    </div>
    <%# .col %>
  <% end %>
</div>
<%# .row %>

app/views/users/_user.html.erb
<div class="row">
  <div class="col-12">
    <div class="card user-info">
      <div class="card-header gradient-card-header">
        <h4><%= current_user.name %></h4>
        <p><%= current_user.email %></p>
      </div>
      <div class="card-body">
        <div class="frame-box">
          <span class="frame-title">合計利用料金</span>
          <h4><%= total_charge(current_user) %>円</h4>
        </div>
        <div class="frame-box">
          <span class="frame-title">利用サービス数</span>
          <h4><%= total_subscription_count(current_user) %>件</h4>
        </div>
        <div class="frame-box">
          <span class="frame-title">通知頻度</span>
          <h4><%= current_user.notification_status_i18n %></h4>
        </div>
        <div class="form-footer text-center mb-2">
          <%= link_to edit_user_registration_path, 'data-toggle' => "popover", 'data-content' => "ユーザー編集" , class: "subscription-info btn btn-success detail-info btn-user-edit" do %>
            <%= fa_icon "user-edit" ,class: "big" %>
          <% end %>
        </div>
      </div>
      <%# /.card-body %>
    </div>
    <%# /.card %>
  </div>
  <%# /.col %>
</div>
<%# /.row %>

app/views/users/show.html.erb
<% provide(:title, "Mypage") %>
<div class="container">
  <div class="row">
    <div class="col-lg-12 add-subscription">
      <%= link_to 'サブスクリプション追加', services_path, class: "btn btn-new my-3" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%# 検索・ソート %>
      <%= render 'search' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
      <div class="row mb-3">
        <div class="col-md-8 ml-3">
          <%= paginate @services %>
        </div>
        <div class="col-md-3 text-right pt-3">
          <span>表示件数 <%= @services.count %>件 / <%= @services.total_count %>件中</span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <%# ユーザー詳細 %>
    <div class="col-md-3 mb-3">
      <%= render 'user' %>
    </div>
    <%# サブスクリプション一覧 %>
    <div class="col-md-9">
      <% if @services.blank? %>
        <%= render 'shared/help' %>
      <% else %>
        <%= render 'subscription' %>
      <% end %>
    </div>
  </div>
</div>
<div id="subscription-show-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>