config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:show]
  
  resources :services do
    post :import, on: :collection
    resources :clips, only: [:create, :destroy]
  end
  
  resources :subscriptions, except: [:index]

  resources :contacts, only: [:new, :create]
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :charge, presence: true, length: { maximum: 10 }, numericality: { greater_than_or_equal_to: 0, less_than: 1_000_00 }
  validates :due_date, presence: true, length: { maximum: 10 }
  validates :note, length: { maximum: 255 }
  validates :service_id, uniqueness: { scope: :user_id }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  include Common
  before_action :set_subscription, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def new
    @subscription = subscriptions.new(service_id: params[:service_id])
  end

  def create
    @subscription = subscriptions.new(subscription_params)
    respond_to do |format|
      if @subscription.save
        @service = Service.find(@subscription.service_id)
        format.html { redirect_to services_path, notice: "「#{service_name(@subscription)}」を追加しました" }
        format.js { @status = 'success' }
      else
        format.html { render :new }
        format.js { @status = 'fail' }
      end
    end
  end

  def show; end

  def edit; end

  def update
    if @subscription.update(subscription_params)
      redirect_to user_path(current_user.id), notice: "「#{service_name(@subscription)}」を更新しました"
    else
      render 'edit'
    end
  end

  def destroy
    @service = Service.find(@subscription.service_id)
    @subscription.destroy
    respond_to do |format|
      if params[:back_to_mypage]
        flash[:alert] = "「#{service_name(@subscription)}」を利用一覧から外しました"
        format.html { redirect_to user_path(current_user) }
      else
        format.html { redirect_to services_path }
      end
      format.js
    end
  end

  private

  def set_subscription
    @subscription = subscriptions.find(params[:id])
  end

  def subscription_params
    params.require(:subscription).permit(:charge, :due_date, :note, :user_id, :service_id)
  end

  def service_name(subscription)
    Service.find_by(id: subscription.service_id).name
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def service(subscription)
    Service.find_by(id: subscription.service_id)
  end

  def total_charge(user)
    Subscription.where(user_id: user.id).sum(:charge)
  end

  def get_subscription_id(user, service)
    user.subscriptions.find_by(service_id: service.id).id
  end
end

app/views/subscriptions/_form.html.erb
<div class="container subscription-form">
  <div class="row">
    <div class="col-12">
      <% if @subscription.errors.any? %>
        <div id="error_explanation">
          <h2><%= @subscription.errors.count %>件のエラーがあります。</h2>
          <ul>
            <% @subscription.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="card">
            <button type="button" class="close text-right" data-dismiss="modal" onfocus="this.blur();">&times;</button>
            <h2 class="form-title">
              <% if params[:id] %>
                編 集
              <% else %>
                登 録
              <% end %>
            </h2>
            <%= form_with model: @subscription, remote: true do |f| %>
              <% service = service(@subscription) %>
              <% unless params[:id] %>
                <%= f.hidden_field :service_id, value: params[:service_id] %>
              <% end %>
              <div class="card-body">
                <div class="row">
                  <div class="col-xs-12 col-md-2 col-lg-3">
                    <% if service.icon.present? %>
                      <div class="service-icon">
                        <%= image_tag service.icon.url %>
                      </div>
                    <% else %>
                      <div class="no-icon">No-Icon</div>
                    <% end %>
                  </div>
                  <div class="col-xs-12 col-md-10 col-lg-9">
                    <div class="row">
                      <div class="col-lg-12">
                        <%= f.label :charge %>
                        <%= f.number_field :charge, in: 0..100000,required: true, class: "" %>円
                      </div>
                      <div class="col-lg-12">
                        <%= f.label :due_date %>
                        <%= f.select :due_date, (1..31).each,placeholder: "due_date", class: "form-control" %>日
                      </div>
                    </div>
                  </div>
                </div>
                <%# .row1 %>

                <div class="row my-2">
                  <div class="col-12">
                    <div class="form-label-group mb-2">
                      <%= f.text_area :note ,placeholder: "備考欄",class: "form-control mt-4" ,rows: 4 %>
                    </div>  
                  </div>
                </div>
                <%# .row3 %>

                <div class="row">
                  <div class="col-12">
                    <div class="button-panel">
                      <%= f.submit class: "btn btn-lg btn-register btn-block mt-3" %>
                    </div>  
                  </div>
                </div>
                <%# .row4 %>
              </div>
              <%# .card-body %>
            <% end %>
          </div>
          <%# .card %>
        </div>
        <%# .modal-content %>
      </div>
      <%# .modal-dialog %>
    </div>
    <%# .col %>
  </div>
  <%# .row %>
</div>

app/views/subscriptions/_index.html.erb
<table class="table table-hover">
  <tr class="thead-light">
    <th id="icon">アイコン</th>
    <th id="name">名前</th>
    <th id="summary">概要</th>
    <th id="category">カテゴリー</th>
    <th id="count">利用者数</th>
    <th id="status">利用状況</th>
    <th id="addition">追加</th>
    <th id="menu" colspan="3">メニュー</th>
  </tr>

  <% @subscriptions.each do |subscription| %>
    <tr>
      <% if subscription.icon.present? %>
        <td><%= image_tag subscription.icon.thumb.url %></td>
      <% else %>
        <td>No-Icon</td>
      <% end %>
      <td><%= subscription.name %></td>
      <td><%= subscription.summary %></td>
      <%# カテゴリー一覧 %>
      <td>
        <% subscription.categories.each do |category|%>
          <%= link_to category.name, subscriptions_path(category_id: category.id), class: "badge badge-primary py-1 px-2" %>
        <% end %>
      </td>
      <%# 利用者数 %>
      <td class="text-center"><%= subscription.additions.count %></td>
      <%# 利用状況 %>
      <td>
        <% if current_user.already_added?(subscription) %>
          利用中
        <% end %>
      </td>
      <%# 追加or解除ボタン %>
      <td>
        <% if current_user.already_added?(subscription) %>
          <%= button_to '解除', subscription_addition_path(subscription, id: current_user.id), method: :delete, remote: true, class: "btn btn-light" %>
        <% else %>
          <%= button_to '追加', subscription_additions_path(subscription), remote: true, class: "btn btn-secondary" %>
        <% end %>
      </td>
      <td>
        <%= link_to '詳細', subscription_path(subscription.id) ,class: "btn btn-info mr-2" %>
        <% if current_user.admin? %>
          <%= link_to '編集', edit_subscription_path(subscription.id) ,class: "btn btn-success mr-2" %>
          <%= link_to '削除', subscription_path(subscription), method: :delete, remote: true, data: { confirm: '本当に削除してもいいですか?' } ,class: "btn btn-danger delete" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/subscriptions/_show.html.erb
<div class="container show-page">
  <div class="row">
    <div class="col-12">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="card p-3">
            <button type="button" class="close text-right" data-dismiss="modal" onfocus="this.blur();">&times;</button>
            <div class="card-body">
              <div class="row">
                <div class="col-md-4 ml-3">
                  <% service = service(@subscription) %>
                  <% if service.icon.present? %>
                    <div class="service-icon">
                      <%= image_tag service.icon.url %>
                    </div>
                  <% else %>
                    <div class="no-icon">No-Icon</div>
                  <% end %>
                </div>
                <div class="col-md-7">
                  <div class="row category">
                    <div class="col-md-12">
                      <% service.categories.each do |category|%>
                        <span class= "badge badge-primary py-1 px-2"><%= category.name %></span>
                      <% end %>
                    </div>
                    <div class="col-md-12">
                      <h3 class="service-title"><%= service.name %></h3>
                    </div>
                  </div>
                </div>
              </div>
              <%# .row1 %>

              <div class="row">
                <div class="col-md-6">
                  <div class="frame-box mb-2 pt-3">
                    <span class="frame-title">利用料金</span>
                    <h5 class="text-center charge-text"><%= @subscription.charge %>円</h5>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="frame-box mb-2 pt-3">
                    <span class="frame-title">支払日</span>
                    <h5 class="text-center due-date-text">毎月 <%= @subscription.due_date %>日</h5>
                  </div>
                </div>
              </div>
              <%# .row2 %>

              <% if @subscription.note.present? %>
                <div class="row">
                  <div class="col-md-12">
                    <div class="frame-box mb-2 pt-3">
                      <span class="frame-title">Note</span>
                      <p class=""><%= @subscription.note %></p>
                    </div>
                  </div>
                </div>
                <% end %>
              <%# .row3 %>

              <div class="row mt-4">
                <div class="col-md-7">
                  <%= link_to service.link, target: :blank, rel: "noopener", "data-toggle" => "popover", "data-content" => "関連リンク", class: "btn btn-link btn-circle detail-info mr-2"  do %>
                    <%= fa_icon "link" %>
                  <% end %>
                </div>
                <div class="col-md-5 text-right mt-3">
                  <span  data-toggle="popover", data-content="利用者数" class="detail-info">
                    <%= fa_icon "users" , class: "mr-2" %><%= service.subscriptions.count %>
                  </span>
                </div>
              </div>
              <%# .row4 %>
            </div>
            <%# .card-body %>
          </div>
          <%# .card %>
        </div>
        <%# .modal-content %>
      </div>
      <%# .modal-dialog %>
    </div>
    <%# .col %>
  </div>
  <%# .row %>
</div>

app/views/subscriptions/create.js.erb
<% if @status == 'success' %>
    $("div#subscription-<%= @service.id %>").addClass("using-service");
    $("span#subscription-btn-<%= @service.id %> span#plus-btn").addClass("display-none");
    $("span#subscription-btn-<%= @service.id %>").append("<%= j(render("shared/minus", service: @service)) %>");
    $("span#users-count-<%= @service.id %>").text("<%= @service.subscriptions.count %>");
<%  elsif @status == 'fail' %>
    alert('既に登録してあります');
<% end %>
$("#subscription-modal").modal("hide");

app/views/subscriptions/destroy.js.erb
$("div#subscription-<%= @service.id %>").removeClass("using-service");
$("span#subscription-btn-<%= @service.id %> span#minus-btn").addClass("display-none");
$("span#subscription-btn-<%= @service.id %>").append("<%= j(render("shared/plus", service: @service)) %>");
$("span#users-count-<%= @service.id %>").text("<%= @service.subscriptions.count %>");

app/views/subscriptions/edit.html.erb
<% provide(:title, "Edit Subscription") %>
<div class="container">
  <div class="new-form">
    
    <%= render 'form' %>
    
  </div>
</div>

app/views/subscriptions/new.js.erb
$("#subscription-modal").html("<%= escape_javascript(render 'form') %>")
$("#subscription-modal").modal("show")

app/views/subscriptions/show.js.erb
$("#subscription-show-modal").html("<%= escape_javascript(render 'show') %>")
$("#subscription-show-modal").modal("show")