config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:show]
  
  resources :services do
    post :import, on: :collection
    resources :clips, only: [:create, :destroy]
  end
  
  resources :subscriptions, except: [:index]

  resources :contacts, only: [:new, :create]
end

app/views/layouts/_flash.html.erb
<div id="flash-message">
  <% if notice %>
    <div class="alert alert-success" >
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" onfocus="this.blur();">&times;</button>
    </div>
  <% elsif alert %>
    <div class="alert alert-danger" >
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert" onfocus="this.blur();">&times;</button>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer text-center bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-inline">
          <li class="list-inline-item">
            <%= link_to "利用規約", page_path('terms') %>
          </li>
          <li class="list-inline-item">
            <%= link_to "プライバシーポリシー", page_path('privacy') %>
          </li>
          <% if current_user %>
            <li class="list-inline-item">
              <%= link_to "お問い合わせ", new_contact_path %>
            </li>
          <% end %>
          <li class="list-inline-item">
            <%= link_to "ヘルプ", page_path('help') %>
          </li>
        </ul>
      </div>
      <div class="col-lg-12" id="copyright">
        <span>© Copyright 2019 Subsc</span>
      </div>
    </div>
  </div>
  <div id="page-top">
    <%= link_to "#" do %>
    <span class="fa-stack fa-2x">
      <i class="fa fa-chevron-circle-up fa-stack-2x"></i>
    </span>
    <% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header container mb-2">
  <nav class="navbar navbar-expand-lg navbar-light">
    <%= link_to "Subsc", root_path, class: "nav-brand nav-link" %>
    
    <button type="button" class="navbar-toggler burger-menu" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
      <%= fa_icon ("bars") , class: "mr-1" %>MENU
    </button>

    <div class="collapse navbar-collapse" id="Navber">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= active_link_to "マイページ", user_path(current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= active_link_to "サービス一覧", services_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= active_link_to "お問い合わせ", new_contact_path, class: "nav-link" %>
          </li>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "管理者メニュー", rails_admin_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link", id: "logout-link"  %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= active_link_to "ログイン", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= active_link_to "新規登録", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Subscとは", root_path(anchor: :feature), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "使い方", root_path(anchor: :step), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= active_link_to "サービス一覧", services_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Subsc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= render 'layouts/flash' %>

    <div class="container my-5">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>